# settings.toml

[tickers]
symbols = ['VGS.AX', 'ETH-AUD', 'BTC-AUD', 'VDHG.AX', 'NDQ.AX', 'IOO.AX']

[analysis]
years_back = 5
y_min = 0

[email]
sender_email = "gmail here"
receiver_email = "gmail here"
additional_email = "additional@example.com"
password = "app specific password here"
subject = "Automated Stock Analysis Report"

[github]
auth_token = "github auth here"